// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/add_contact.tsx";
import * as $3 from "./routes/api/contacts/[contact_id].tsx";
import * as $4 from "./routes/contacts.tsx";
import * as $5 from "./routes/home.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login/index.tsx";
import * as $8 from "./routes/logout.tsx";
import * as $9 from "./routes/megan.tsx";
import * as $10 from "./routes/oak.tsx";
import * as $11 from "./routes/signup.tsx";
import * as $$0 from "./islands/Contact.tsx";
import * as $$1 from "./islands/ContactList.tsx";
import * as $$2 from "./islands/ContactListModal.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/ItemsContainer.tsx";
import * as $$5 from "./islands/Pagination.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/add_contact.tsx": $2,
    "./routes/api/contacts/[contact_id].tsx": $3,
    "./routes/contacts.tsx": $4,
    "./routes/home.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login/index.tsx": $7,
    "./routes/logout.tsx": $8,
    "./routes/megan.tsx": $9,
    "./routes/oak.tsx": $10,
    "./routes/signup.tsx": $11,
  },
  islands: {
    "./islands/Contact.tsx": $$0,
    "./islands/ContactList.tsx": $$1,
    "./islands/ContactListModal.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/ItemsContainer.tsx": $$4,
    "./islands/Pagination.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
