// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/account/index.tsx";
import * as $5 from "./routes/account/manage.ts";
import * as $6 from "./routes/account/upgrade.ts";
import * as $7 from "./routes/api/_middleware.ts";
import * as $8 from "./routes/api/comments.ts";
import * as $9 from "./routes/api/contacts/[id]/index.ts";
import * as $10 from "./routes/api/contacts/index.ts";
import * as $11 from "./routes/api/contacts/seed.ts";
import * as $12 from "./routes/api/items/[id]/comments.ts";
import * as $13 from "./routes/api/items/[id]/index.ts";
import * as $14 from "./routes/api/items/[id]/vote.ts";
import * as $15 from "./routes/api/items/index.ts";
import * as $16 from "./routes/api/me/notifications.ts";
import * as $17 from "./routes/api/me/votes.ts";
import * as $18 from "./routes/api/stripe-webhooks.ts";
import * as $19 from "./routes/api/users/[login]/index.ts";
import * as $20 from "./routes/api/users/[login]/items.ts";
import * as $21 from "./routes/api/users/index.ts";
import * as $22 from "./routes/blog/[slug].tsx";
import * as $23 from "./routes/blog/index.tsx";
import * as $24 from "./routes/contacts/[id]/edit.tsx";
import * as $25 from "./routes/contacts/index.tsx";
import * as $26 from "./routes/contacts/new.tsx";
import * as $27 from "./routes/dashboard/index.tsx";
import * as $28 from "./routes/feed.ts";
import * as $29 from "./routes/index.tsx";
import * as $30 from "./routes/items/[id].tsx";
import * as $31 from "./routes/login.tsx";
import * as $32 from "./routes/notifications/[id].ts";
import * as $33 from "./routes/notifications/index.tsx";
import * as $34 from "./routes/pricing.tsx";
import * as $35 from "./routes/submit.tsx";
import * as $36 from "./routes/users/[login].tsx";
import * as $$0 from "./islands/Chart.tsx";
import * as $$1 from "./islands/CommentsList.tsx";
import * as $$2 from "./islands/ContactForm.tsx";
import * as $$3 from "./islands/ContactsList.tsx";
import * as $$4 from "./islands/DashboardList.tsx";
import * as $$5 from "./islands/DashboardUpcomingList.tsx";
import * as $$6 from "./islands/ItemsList.tsx";
import * as $$7 from "./islands/NotificationsList.tsx";
import * as $$8 from "./islands/UsersTable.tsx";
import * as $$9 from "./islands/VoteButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/account/index.tsx": $4,
    "./routes/account/manage.ts": $5,
    "./routes/account/upgrade.ts": $6,
    "./routes/api/_middleware.ts": $7,
    "./routes/api/comments.ts": $8,
    "./routes/api/contacts/[id]/index.ts": $9,
    "./routes/api/contacts/index.ts": $10,
    "./routes/api/contacts/seed.ts": $11,
    "./routes/api/items/[id]/comments.ts": $12,
    "./routes/api/items/[id]/index.ts": $13,
    "./routes/api/items/[id]/vote.ts": $14,
    "./routes/api/items/index.ts": $15,
    "./routes/api/me/notifications.ts": $16,
    "./routes/api/me/votes.ts": $17,
    "./routes/api/stripe-webhooks.ts": $18,
    "./routes/api/users/[login]/index.ts": $19,
    "./routes/api/users/[login]/items.ts": $20,
    "./routes/api/users/index.ts": $21,
    "./routes/blog/[slug].tsx": $22,
    "./routes/blog/index.tsx": $23,
    "./routes/contacts/[id]/edit.tsx": $24,
    "./routes/contacts/index.tsx": $25,
    "./routes/contacts/new.tsx": $26,
    "./routes/dashboard/index.tsx": $27,
    "./routes/feed.ts": $28,
    "./routes/index.tsx": $29,
    "./routes/items/[id].tsx": $30,
    "./routes/login.tsx": $31,
    "./routes/notifications/[id].ts": $32,
    "./routes/notifications/index.tsx": $33,
    "./routes/pricing.tsx": $34,
    "./routes/submit.tsx": $35,
    "./routes/users/[login].tsx": $36,
  },
  islands: {
    "./islands/Chart.tsx": $$0,
    "./islands/CommentsList.tsx": $$1,
    "./islands/ContactForm.tsx": $$2,
    "./islands/ContactsList.tsx": $$3,
    "./islands/DashboardList.tsx": $$4,
    "./islands/DashboardUpcomingList.tsx": $$5,
    "./islands/ItemsList.tsx": $$6,
    "./islands/NotificationsList.tsx": $$7,
    "./islands/UsersTable.tsx": $$8,
    "./islands/VoteButton.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
