// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/count.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login/index.tsx";
import * as $4 from "./routes/need_auth.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/count.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/login/index.tsx": $3,
    "./routes/need_auth.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
