create table "public"."todos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "description" text not null,
    "done" boolean not null default false,
    "email" text not null
);


alter table "public"."todos" enable row level security;

CREATE UNIQUE INDEX todos_pkey ON public.todos USING btree (id);

alter table "public"."todos" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";

create policy "Full access for authenticated users to their own data"
on "public"."todos"
as permissive
for all
to authenticated
using (((auth.jwt() ->> 'email'::text) = email))
with check (((auth.jwt() ->> 'email'::text) = email));




