create table "public"."contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "first_name" character varying,
    "last_name" character varying,
    "email" text,
    "phone" character varying,
    "birthday_day" smallint,
    "birthday_month" smallint,
    "birthday_year" smallint,
    "owner_email" text not null
);


alter table "public"."contacts" enable row level security;

CREATE UNIQUE INDEX contacts_pkey ON public.contacts USING btree (id);

alter table "public"."contacts" add constraint "contacts_pkey" PRIMARY KEY using index "contacts_pkey";

create policy "Enable update for users based on owner_email"
on "public"."contacts"
as permissive
for all
to authenticated
using (((auth.jwt() ->> 'email'::text) = owner_email))
with check (((auth.jwt() ->> 'email'::text) = owner_email));
