name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies, cache them correctly
      
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
        with:
          # build: npm run build
          start: npm test
